# Jekyll settings
permalink: /:year/:month/:title/
pygments: true
markdown: rdiscount
paginator: true
exclude: ["bin", "README.md", "LICENSE.md", "Gemfile", "Gemfile.lock"]

# Site settings
url: http://leon.radley.se
title: Leon Radley
description: "Blog of Leon Radley, professional web developer"
author: Leon Radley
simple_search: http://google.com/search

# Navigation
navigation:
- text: Blog
  url: /
- text: Labs
  url: /labs/